// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5FjDoMBQr6mPbAPC5nJ0UzA22vwO_VUc',
    appId: '1:435363878173:web:2e72a6c27cbf7acefbfdf4',
    messagingSenderId: '435363878173',
    projectId: 'fittrack-ccat',
    authDomain: 'fittrack-ccat.firebaseapp.com',
    databaseURL: 'https://fittrack-ccat-default-rtdb.firebaseio.com',
    storageBucket: 'fittrack-ccat.appspot.com',
    measurementId: 'G-VN06E5DHZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy0NSEApL4P2xKnSSkfW9zHdnTEEuOGY4',
    appId: '1:435363878173:android:fda63038c9ae5217fbfdf4',
    messagingSenderId: '435363878173',
    projectId: 'fittrack-ccat',
    databaseURL: 'https://fittrack-ccat-default-rtdb.firebaseio.com',
    storageBucket: 'fittrack-ccat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr8SJYr8Cn592U7bPn5ke0ZucL07YebpQ',
    appId: '1:435363878173:ios:9ae281c0e6cc0bd9fbfdf4',
    messagingSenderId: '435363878173',
    projectId: 'fittrack-ccat',
    databaseURL: 'https://fittrack-ccat-default-rtdb.firebaseio.com',
    storageBucket: 'fittrack-ccat.appspot.com',
    iosClientId: '435363878173-revgnaokcgp9i6vulo04crlfttotupl9.apps.googleusercontent.com',
    iosBundleId: 'com.ccat.fitTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr8SJYr8Cn592U7bPn5ke0ZucL07YebpQ',
    appId: '1:435363878173:ios:9ae281c0e6cc0bd9fbfdf4',
    messagingSenderId: '435363878173',
    projectId: 'fittrack-ccat',
    databaseURL: 'https://fittrack-ccat-default-rtdb.firebaseio.com',
    storageBucket: 'fittrack-ccat.appspot.com',
    iosClientId: '435363878173-revgnaokcgp9i6vulo04crlfttotupl9.apps.googleusercontent.com',
    iosBundleId: 'com.ccat.fitTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5FjDoMBQr6mPbAPC5nJ0UzA22vwO_VUc',
    appId: '1:435363878173:web:ad664061198069a2fbfdf4',
    messagingSenderId: '435363878173',
    projectId: 'fittrack-ccat',
    authDomain: 'fittrack-ccat.firebaseapp.com',
    databaseURL: 'https://fittrack-ccat-default-rtdb.firebaseio.com',
    storageBucket: 'fittrack-ccat.appspot.com',
    measurementId: 'G-83X8XL4GE0',
  );

}